- src/app/apply/branching/page.tsx
- src/app/apply/page.tsx
- src/app/apply/personal/page.tsx
- src/app/apply/template.tsx
- src/app/page.tsx
- src/components/footer/Footer.tsx
- src/components/header/progressHeader/ProgressHeader.tsx
- src/pages/common/LastStep.tsx
- src/store/feature/applyInfo.ts
- 3대3 미팅종류 선택 페이지를 작성했습니다.
- 각 팅별 질문 선택 이전 step 변경 로직을 작성하였습니다.
close #32
> Feat/group choice page - #32

- src/app/apply/complete/page.tsx
- src/app/apply/group/page.tsx
- src/app/apply/template.tsx
- src/components/footer/Footer.tsx
- 신청 완료 페이지를 변경된 header 로직에 맞게 개선하였습니다.
close #37
> Feat/improve complete page - #37

- src/app/apply/branching/page.tsx
- src/app/apply/complete/page.tsx
- src/app/apply/page.tsx
- src/components/buttons/button/Button.tsx
- Button 컴포넌트 textSize props을 추가하여 사이즈 표시를 개선했습니다
- textSize base: { font-size: 20px }
- textSize sm: { font-size: 16px }
close #39
> feat: Button 컴포넌트 textSize props 추가 - #39

- src/app/apply/groupLeader/page.tsx
- src/app/apply/groupMember/page.tsx
- src/components/header/progressHeader/ProgressHeader.tsx
- src/components/index.ts
- src/components/input/dropdownInput/DropdownInput.style.tsx
- src/components/input/dropdownInput/DropdownInput.tsx
- src/components/molecules/departmentSelectBox/DepartmentSelectBox.tsx
- src/constants/index.ts
- src/page/common/ConfirmStep.tsx
- src/page/common/applyMyInfoStep/index.tsx
- src/page/groupLeader/FourthStep/FirstPage.tsx
- src/page/groupLeader/FourthStep/index.tsx
- src/page/groupMember/SecondStep/FirstPage.tsx
- src/page/groupMember/SecondStep/index.tsx
- DropdownInput 컴포넌트 개선 
- 모든 prop을 필수로 받게 변경하였습니다.
- 항목 선택 시 input 안에 label을 변경하는 로직을 추가하였습니다.
- 불필요한 style 파일의 타입 지정을 제거하였습니다.
- DepartmentSelectBox 컴포넌트의 내부 label 문구를 변경하였습니다.
- 3대3 미팅 팅원 페이지를 작성하고 스텝 변경 로직을 구현하였습니다.
> feat: group state management - #56

- src/components/molecules/slider/Slider.style.tsx
- src/components/molecules/slider/Slider.tsx
- slider 컴포넌트를 작성하였습니다.
close #51
> feat: slider component 작성 - #51

- src/components/molecules/departmentSelectBox/DepartmentSelectBox.tsx
- src/page/personal/ThirdStep/SecondPage.tsx
1. departmentSelectBox에서 최대 5개까지 선택할 수 있도록 개수 제한을 설정했습니다.
1. 매칭을 원하지 않는 학과 입력 제작
2. 선호하는 상대의 흡연 여부 선택 제작
close #98
> feat: 1대1 step3 page2 선호 상대 정보 입력하기 페이지 제작

- src/app/page.tsx
- src/components/molecules/resultBox/ResultBox.tsx
- src/hooks/useClickButton.ts
- src/page/personal/ThirdStep/FourthPage.tsx
- useRouter함수 중복선언, 변수명 불일치로 발생하는 에러 해결
- else if로 처리하지 않아 발생한 버튼 클릭 중복으로 안되는 문제 해결
- 선호 mbti 선택 페이지 4종류의 mbti 구분 모두 선택 시 제출되도록 로직 변경
close #112
> feat: mbti prefer order - #112

- src/types/information.type.ts
- src/utils/information.ts
> feat: Binary로 바꾸는 parser 만들기

- src/api/services/Meeting.type.ts
- src/api/services/MeetingAPI.ts
- src/api/services/types.ts
- src/api/types/meeting.type.ts
- src/app/applicationInfo/page.tsx
- src/app/apply/branching/page.tsx
- src/app/page.tsx
- src/components/footer/Footer.tsx
- src/components/modal/bottomSheet/BottomSheet.tsx
- src/components/molecules/resultBox/ResultBox.tsx
- src/components/molecules/teamStatusBox/TeamStatusBox.tsx
- src/page/common/applyMyInfoStep/FirstPage.tsx
- src/page/groupLeader/SecondStep/FirstPage.tsx
- src/page/groupLeader/SecondStep/SecondPage.tsx
- src/page/groupMember/SecondStep/FirstPage.tsx
- src/page/personal/FirstStep/FourthPage.tsx
- src/page/personal/ThirdStep/SecondPage.tsx
- src/store/feature/common/commonReducer.ts
- src/store/feature/meetingType/groupReducer.ts
- src/store/feature/meetingType/personalReducer.ts
- [feat: 모든 store에 초기화 함수 추가](https://github.com/uoslife/client-meeting-season3/commit/6c816eaaf1d60c0b2c171ac5dd6dde5bc06daa91)
- [feat: 메인에서 getUser api 호출](https://github.com/uoslife/client-meeting-season3/commit/a07c30666b4304a94465a96aee1a1fe8c85c9216)
- [feat: 결과 확인페이지 api 관련 로직 작성](https://github.com/uoslife/client-meeting-season3/commit/1f363d3b216010f678e1fd3f0d63f4fcc35420ee)
- [feat: branch에서 api 요청 삭제](https://github.com/uoslife/client-meeting-season3/commit/5e37b14ee466b90663af23629f3605f88c5f2cd6)
- [feat: user관련 api 작성](https://github.com/uoslife/client-meeting-season3/commit/834e0886d76a6ce150f4ef75dcc0226b0fd708f7)
- [fix: 중앙정렬 안맞는 부분 수정](https://github.com/uoslife/client-meeting-season3/commit/38fb1115255d597490f4203b3da173360d675a5c)
- [feat: delete …
> add updated api - #124

- src/app/apply/branching/page.tsx
- src/app/apply/page.tsx
- src/app/page.tsx
- src/components/footer/Footer.tsx
- src/components/modal/toast/Toast.tsx
- [feat: 미팅 타입 선택시 변경 불가 안내 문구 추가](https://github.com/uoslife/client-meeting-season3/commit/7d1bb4291821e980f83348f0174ab746922a44cd)
- [refactor: modalOpen 변수명 수정](https://github.com/uoslife/client-meeting-season3/commit/9d99a94e6dcfd52761b1f0d0a394ee1ea54c9158)
- [feat: 뒤로가기 막는 로직 추가](https://github.com/uoslife/client-meeting-season3/commit/4175a96a85e4e5b94b474b2cf1ba63416057e953)
- [feat: Toast 스타일 및 지속시간 수정](https://github.com/uoslife/client-meeting-season3/commit/e0956015a4f3afae899f8e66d4674a39553ecb97)
close #118
> unable return meeting type - #118

- src/components/footer/Footer.tsx
- src/page/groupLeader/SecondStep/FirstPage.tsx
- [feat: 팅 이름 설정시 2자리 이상이 되도록 로직 추가](https://github.com/uoslife/client-meeting-season3/commit/2e8968d0a051e0071767967708b0335c6d158e39)
close #122
> feat: 팅 이름 설정시 2자리 이상이 되도록 로직 추가 - #122

- src/api/core/index.ts
- src/app/layout.tsx
- src/app/page.tsx
- src/components/molecules/resultBox/ResultBox.tsx
- src/styles/pages/page.style.tsx
- [feat: 401 에러시 시대생 메인으로 redirect](https://github.com/uoslife/client-meeting-season3/commit/b794d7703f500c4255a1f87560fa5445bc0cfe9f)
- [fix: 나이 결괏값 보여질 때 NaN 뜨는 문제 해결](https://github.com/uoslife/client-meeting-season3/commit/d9bb9496abea3508db0886c3c3b035408e7313c9)
- [design: 메인페이지 안내 날짜 변경](https://github.com/uoslife/client-meeting-season3/commit/d996ab37c76be521d1567a0ea7d3f74bb26f08b3)
- [feat: 뒤로가기 막는 로직 추가](https://github.com/uoslife/client-meeting-season3/pull/131/commits/031e20ade08fcfe0c246049f234cb2e0bfe32b15)
> feat: 배포 전 마지막 수정 일부 구현 - #129

- src/api/types/meeting.type.ts
- src/app/applicationInfo/page.tsx
- src/app/page.tsx
- src/page/common/ConfirmStep.tsx
- src/utils/index.ts
- [feat: 결과 확인 페이지 teamStatus 확인 로직 추가](https://github.com/uoslife/client-meeting-season3/commit/936149a0ff433d96e83793f5d5b7a7f74ede3600)
- [feat: 신청 정보 확인 페이지 로직 수정 및 추가](https://github.com/uoslife/client-meeting-season3/commit/c5043ca6a665fe81d2337b18bb02a02b860744c6)
- [feat: 메인페이지 신청 했을 때 버튼 변경](https://github.com/uoslife/client-meeting-season3/commit/cf0774db528591be195786841a0383e4c5d0e702)
- [feat: teamType 타입 수정](https://github.com/uoslife/client-meeting-season3/commit/4628f0544dfad16cba370d545a4ba3cdf582d208)
- [feat: userData를 teamStatus로 변경하는 함수 작성](https://github.com/uoslife/client-meeting-season3/commit/44155aa12e8310bd2793a75713b5d7fb2c84b218)
> feat: final change - #129

- src/constants/departments.ts
- src/page/common/ConfirmStep.tsx
- src/types/information.type.ts
- src/utils/binary/informationToBinary.ts
1. 학과 array 순서 수정
1. 수정된 notion의 binaryToInformation 반영 
1. 키
1. 3자리 정수
2. Q&A
1. 8bit
2. 2+2+2+2
3. MBTI
1. 8bit
2. EINSFTJP
4. 동물상
1. 9bit
2. 해당 동물에 1 표기
3. 최대 2개
5. 관심사
1. 10bit
2. 해당 관심사에 1 표기
3. 3개
1. 나이
1. 16bit
2. 20살부터 35살
2. 흡연
1. 2bit
2. 흡연 10, 비흡연 01
3. 과
1. 39bit
4. 신분
1. 3bit
2. 학부생 100 대학원 010 졸업 001
1. 키(범위)
1. 시작범위 3자리 int
2. 종료범위 3자리 int
2. MBTI
1. 8bit
3. 동물
1. 9bit
1. 나이(범위)
1. 시작범위 16bit
2. 종료범위 16bit
2. 흡연
1. 3bit
2. 흡연 100 비흡연 010 상관없이 001
3. 학과
1. 39bit
4. 신분
1. 3bit
2. 학부생 100 대학생 010 졸업 001
1. 요일
1. 7bit
2. Q&A
1. 10bit
2. 2+2+3+3
1. 나이
1. 32bit
2. 16 + 16
2. 학과
1. 39bit
3. 분위기
1. 3bit
> Feat/ 133-binaryToInformation 최종 수정

- src/api/types/meeting.type.ts
- src/app/applicationInfo/page.tsx
- src/app/layout.tsx
- src/components/molecules/resultBox/ResultBox.tsx
- src/page/common/ConfirmStep.tsx
- src/types/information.type.ts
- src/utils/binary/binaryToInfomation.ts
- src/utils/index.ts
- [fix: onpopstate client side일 때 동작하도록 수정](https://github.com/uoslife/client-meeting-season3/commit/96159d36e4e6e9d8aa76897e3fac5da83237b223)
- [feat: getTeamInfo 에서 teamName 추가](https://github.com/uoslife/client-meeting-season3/commit/242994c599e5e4a9810989b2cf01f1679475c88e)
- [feat: binary To Information](https://github.com/uoslife/client-meeting-season3/commit/70dea43079be9bf3fcbde0a20a5e1d24c5d42482)
close #135
> feat: binary to information - #135

- src/app/layout.tsx
- src/components/footer/Footer.tsx
- src/components/modal/toast/Toast.tsx
- src/page/common/applyMyInfoStep/FirstPage.tsx
- src/page/common/applyMyInfoStep/index.tsx
- src/page/personal/FirstStep/index.tsx
- src/page/personal/ThirdStep/FirstPage.tsx
- src/store/feature/meetingType/personalReducer.ts
- src/utils/binary/informationToBinary.ts
- [feat: 팅원 신청 완료시 common state 초기화](https://github.com/uoslife/client-meeting-season3/commit/35e60821bffe13425157b8075e0fa19789be0c72)
> bug fix - #139

- src/app/layout.tsx
- src/components/footer/Footer.tsx
- src/components/modal/toast/Toast.tsx
- src/page/common/applyMyInfoStep/FirstPage.tsx
- src/page/common/applyMyInfoStep/index.tsx
- src/page/personal/FirstStep/FourthPage.tsx
- src/page/personal/FirstStep/index.tsx
- src/page/personal/ThirdStep/FirstPage.tsx
- src/store/feature/meetingType/personalReducer.ts
- src/utils/binary/informationToBinary.ts
- [feat: 비정상적인 접근시 신청 취소 가능하도록 기능 추가](https://github.com/uoslife/client-meeting-season3/commit/8f1f834d1274986c3e7040811fdf96207b856358) : 마지막 제출시 400 에러 발생하면 신청 취소하는 api 추가
> feat: bug fix - #139

- src/app/layout.tsx
- src/components/footer/Footer.tsx
- src/components/modal/toast/Toast.tsx
- src/page/common/applyMyInfoStep/FirstPage.tsx
- src/page/common/applyMyInfoStep/index.tsx
- src/page/personal/FirstStep/FourthPage.tsx
- src/page/personal/FirstStep/index.tsx
- src/page/personal/ThirdStep/FirstPage.tsx
- src/store/feature/meetingType/personalReducer.ts
- src/utils/binary/informationToBinary.ts
- src/utils/index.ts
- [fix: 신청 정보 확인페이지에서 대학원생은 졸업생으로 표시되는 문제 해결](https://github.com/uoslife/client-meeting-season3/commit/7d2f525258714dede065700faafb0e751728c1d5) : changeStudentType 함수에 '대학원생' return 추가
> fix: bug fix - #139

- src/app/applicationInfo/page.tsx
- src/app/apply/complete/page.tsx
- src/app/page.tsx
- src/components/modal/toast/Toast.tsx
- 6/1 오후 2시로 신청 연장 안내문구 모달 팝업 추가
- 신청 취소기한 문구 변경
-  메인페이지 신청 기간 날짜 변경
close #152
> feat: 신청 연장 관련 문구 수정 - #152

- src/app/applicationInfo/page.tsx
- src/app/page.tsx
- [feat: 신청 취소 버튼 삭제](https://github.com/uoslife/client-meeting-season3/commit/c7867ad2b638e90f8ad622d95ff7164c2999e142)
- [feat: 연장 안내 모달 삭제 및 미신청 유저 신청 마감 모달 추가](https://github.com/uoslife/client-meeting-season3/commit/35d4d8848b7d7e9283811b039a8f5c430dbc3d18)
- [feat: 신청 정보 페이지 매칭중 안내 모달 추가](https://github.com/uoslife/client-meeting-season3/commit/3fc77038f5a73fa1f0ebad79bf4a5ac86f6a496d)
close #151
> feat: apply finish - #151

- src/app/apply/result/page.tsx
- src/app/apply/template.tsx
- src/components/index.ts
- src/components/molecules/teamResultBox/TeamResultBox.style.tsx
- src/components/molecules/teamResultBox/TeamResultBox.tsx
- 결과 페이지 만듬
- API 연결 및 변수 처리 안함 정말 view만 ,, 
- 신청 실패 페이지 안만듬
> feat: apply result page
